### PR TITLE
Add Info about template RAMS

### PR DESCRIPTION
**Pull request by garethhay**
Add Paperwork folder. 

Add Book of Paperwork description to README.md of Hackspace Owners Manual. 

Add README.md to Paperwork. Describe RAMS and add link

### CODE REVIEW

**Comment by idnorton** [comment]
Hi @garethhay hay thanks for the contribution.

You've referenced a file in your PR on the FizzPOP site. Can we include a copy of that file rather than referencing an external site?

**Comment by amunizp** [comment]
Licence might not be compatible? I say leave it referenced so that it can be updated separately?

**Comment by idnorton** [comment]
@amunizp Author is happy to include the files but his github isn't linked to his telegram account and it didn't land back here ;)

**Comment by garethhay** [comment]
For reference, released under MIT license so do with as you wish.

**Comment by amunizp** [comment]
My bad, thought MIT was only for code.

**Review by proffalken — APPROVED** [review]
Approving this as part of a general reshuffle, apologies it's taken so long

**Pull request merged**
